# Generated by Django 4.2.6 on 2023-10-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_dreessingroom_alter_movie_actors_actor_dressing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DreessingRoom',
            new_name='DressingRoom',
        ),
    ]
